### ISSUE TITLE
500 Error when reviewing with multiple roles

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3255]
**Describe the bug**

When submitting a review as someone who is a Staff Admin, Reviewer, and Community Reviewer, a 500 error happens.

**To Reproduce**

1. Create a user who has multiple review capable roles (Staff Admin, Reviewer, and Community Reviewer)
2. Create a fund/round/application and move it to the review process
3. Attempt to review as that user

**Expected behavior**

Review is left

**Priority**

This was high for our client because there is some overlap between the people administrating hypha and the ones.  But we resolved it in our fork.

**Affected roles**

- Staff
- Reviewers

**Screenshots**

This is the error:

```
Traceback (most recent call last):
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

During handling of the above exception (AssignedReviewers matching query does not exist.), another exception occurred:
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (duplicate key value violates unique constraint "funds_assignedreviewers_submission_id_reviewer_id_a60bc37a_uniq"
DETAIL:  Key (submission_id, reviewer_id)=(7, 13) already exists.
) was the direct cause of the following exception:
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/hypha/apply/review/views.py", line 144, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/hypha/apply/utils/views.py", line 242, in post
    return super().post(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/ots-ardc/vanilla-hypha/hypha/apply/review/views.py", line 170, in form_valid
    form.instance.author, _ = AssignedReviewers.objects.get_or_create_for_user(
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/hypha/apply/funds/models/submissions.py", line 1064, in get_or_create_for_user
    return self.get_or_create(
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /apply/submissions/7/review/
Exception Value: duplicate key value violates unique constraint "funds_assignedreviewers_submission_id_reviewer_id_a60bc37a_uniq"
DETAIL:  Key (submission_id, reviewer_id)=(7, 13) already exists.
```

**Additional context**

The additional context from the research in our internal tracker:

> Here's what I think is happening: When a user goes to create a review, Hypha checks to see if the user was assigned as a reviewer and tries to creates that assignment. But because the reviewer's group is stored in the assignment, and because when the reviewer is first assigned the bulk create doesn't use the same logic logic to compute that group, it tries to create a new assignment with a different group but errors because an assignment already exists. This proposed change uses the same group logic in both cases and updates if an assignment exists.

We also have a fix that will come in a PR

**Comment by frjo** [comment]
@frankduncan  I can replicate this.

But why do a user need all these roles? If you are staff you can already do everything and have no need to have roles like "reviewer".

The "community reviewer" functionality was developed some time back but never used as far as I know so very likly have issues.
