### ISSUE TITLE
When a review with no score exists, "View All" reviews breaks with 500 error

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3314]
**Describe the bug**

When making a review with a score, and don't enter score (N/A option), looking at "View All" for the reviews causes a 500 error.

**To Reproduce**

1. Go to an active submission
2. Enter a review when the review has a score field (Specifically "Score without Text")
3. Don't put in a score (leave default N/A option)
4. When on submission page, under reviews, click "View All"

**Expected behavior**

The normal View All screen shoudl show

**Affected roles**

- Reviewers

**Screenshots**

```
Environment:


Request Method: GET
Request URL: http://ots-ardc-test.com/apply/submissions/16/reviews/

Django Version: 3.2.18
Python Version: 3.10.0
Installed Applications:
['scout_apm.django',
 'hypha.cookieconsent',
 'hypha.images',
 'hypha.core.apps.CoreAppConfig',
 'hypha.apply.activity',
 'hypha.apply.categories',
 'hypha.apply.funds',
 'hypha.apply.dashboard',
 'hypha.apply.flags',
 'hypha.apply.home',
 'hypha.apply.users',
 'hypha.apply.review',
 'hypha.apply.determinations',
 'hypha.apply.stream_forms',
 'hypha.apply.utils.apps.UtilsConfig',
 'hypha.apply.projects.apps.ProjectsConfig',
 'hypha.public.funds',
 'hypha.public.home',
 'hypha.public.mailchimp',
 'hypha.public.navigation',
 'hypha.public.news',
 'hypha.public.people',
 'hypha.public.projects',
 'hypha.public.search',
 'hypha.public.standardpages',
 'hypha.public.forms',
 'hypha.public.utils',
 'hypha.public.partner',
 'social_django',
 'django_htmx',
 'django_web_components',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.settings',
 'wagtail.contrib.search_promotions',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail',
 'anymail',
 'modelcluster',
 'taggit',
 'django_extensions',
 'tinymce',
 'django_tables2',
 'django_filters',
 'django_select2',
 'addressfield',
 'django_bleach',
 'django_fsm',
 'django_pwned_passwords',
 'django_slack',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'two_factor',
 'drf_yasg',
 'rest_framework',
 'rest_framework_api_key',
 'wagtailcache',
 'wagtail_purge',
 'django_file_form',
 'hijack',
 'pagedown',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.postgres',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django.forms',
 'formtools',
 'wagtail.contrib.styleguide',
 'debug_toolbar',
 'django_browser_reload']
Installed Middleware:
['django_browser_reload.middleware.BrowserReloadMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_referrer_policy.middleware.ReferrerPolicyMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'hypha.apply.users.middleware.TwoFactorAuthenticationMiddleware',
 'hijack.middleware.HijackUserMiddleware',
 'hypha.apply.users.middleware.SocialAuthExceptionMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'hypha.apply.middleware.apply_url_conf_middleware',
 'hypha.apply.middleware.HandleProtectionErrorMiddleware',
 'django_htmx.middleware.HtmxMiddleware']



Traceback (most recent call last):
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ots-ardc/vanilla-hypha/venv/hypha/lib/python3.10/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/ots-ardc/vanilla-hypha/hypha/apply/review/views.py", line 407, in get_context_data
    review_data[field.id]['answers'][i] = field.block.render(None, {'data': data})
  File "/home/ots-ardc/vanilla-hypha/hypha/apply/review/blocks.py", line 84, in render
    data = int(context['data'])

Exception Type: ValueError at /apply/submissions/16/reviews/
Exception Value: invalid literal for int() with base 10: ''
```

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser: Firefox
 - Version: 109.0.1

**Comment by frankduncan** [comment]
Small note: This isn't based on an issue that ARDC ran into, it's just something I found while I was testing one of the other bugs we had fixes for.
