### ISSUE TITLE
Results page errors when invalid number in Requested Amount field

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3787]
**Describe the bug**

If non standard numbers get added to the requested amount field, the page at apply/submissions/result/ errors with the following error:

```
[ERROR][django.request] Internal Server Error: /apply/submissions/result/
Traceback (most recent call last):
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "124.000.00"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(filter=self.filterset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/upstream-hypha/hypha/apply/funds/views.py", line 1728, in get_context_data
    submission_values = self.object_list.value()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/upstream-hypha/hypha/apply/funds/models/submissions.py", line 210, in value
    ).aggregate(
      ^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/models/query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ots-ardc/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.DataError: invalid input syntax for type double precision: "124.000.00"

```

**To Reproduce**

1. Create a fund/round/application with Requested Value field
2. Insert a non standard number, like "99.000.00" into the value field.  In order to submit the application, you'll need to either be using a locale where javascripts isNaN function accepts that, or turn off the javascript event for the input
3. Submit the application, and move it all the way to the "Accepted" determination status.
4. Go to results page
5. See error

**Expected behavior**

Either one of two things.

1. Have server side checking/processing for this field when saving, to ensure that it is a valid number (wagtail is saving it as a string in the database as it does everything).
2. Change the sql query, with something like the following:
```
+            value_as_string=KeyTextTransform("value", "form_data")
+        ).annotate(
+            value_numeric_only=Func(
+                "value_as_string",
+                Value('[^0-9.]'),
+                Value(''),
+                Value('g'),
+                function="REGEXP_REPLACE",
+                output_field=models.FloatField()
             )
+        ).annotate(
+            value=Cast("value_numeric_only", output_field=FloatField()),

```

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff

**Desktop (please complete the following information):**

 - OS: Debian Linux
 - Browser: Firefox
 - Version: 122

**Additional context**

Note, this kind of value also causes an error in the projects world, because it's used as a number when creating a project.

**Comment by frjo** [comment]
I would prefer to add server side validation to make sure the value is a number before it is saved to the db.

**Comment by frankduncan** [comment]
For one of our clients, they actually asked us to allow non numerics, so that people could put in "$123,456.89" and for it to show up in the application just as typed in.
